### ISSUE TITLE
Add ROUTERADVERT to reasons

### ISSUE THREAD

**Issue by SpareSimian** [DanielG/dhcp-policy-routing#3]
I discovered empirically with a Raspberry Pi running Buster x64 that ROUTERADVERT is the reason when one issues "ip link set dev eth1 [down|up]" to bounce an interface for testing. So I suggest adding that to the case with "BOUND|REBOOT".

**Comment by DanielG** [comment]
I don't really get what you're saying. Should ROUTERADVERT just be ignored, or what?

**Comment by SpareSimian** [comment]
I issue ""ip link set dev eth1 down" then ""ip link set dev eth1 up" to simulate a hotplug event and the script is invoked with reason ROUTERADVERT, not BOUND or REBOOT. So I'm suggesting adding ROUTERADVERT to the interface-up case.

**Comment by DanielG** [comment]
Hmm, I would expect to see a RENEW or REBOOT in that case regardless. Can you add logging to see what state transitions you get exactly in that case?

Note: It's easiest to log to a file with something like `echo whatever >>/tmp/dhcp.log`

**Comment by SpareSimian** [comment]
You're right. The ROUTERADVERT seems to be noise, and I'm indeed getting a BOUND event, just fairly long after I bring the link up. Sorry for the false alarm.
